### ISSUE TITLE
Cannot send a test message to the "from" address of my newsletter

### ISSUE THREAD

**Issue by edenenterprise** [Sandglaz/maktoub#14]
Hello maktoub-Team!

I have setup maktoub exactly as in the documentation.
I put "gem maktoub" in my Gemfile, "bundle install" it, generated the maktoub:config.

my maktoub.rb looks like this:
http://pastebin.com/gmGNcBXx

i put newsletter_test.html.erb in app/views/maktoub/newsletters/
and then I did this command in the console:

    rake maktoub:mail['newsletter_test'] --trace

and this was the output

http://pastebin.com/iW0A7V39

**Comment by zawaideh** [comment]
you need to have subscribers_extractor defined. This is what defined who the newsletter gets sent to.

**Comment by edenenterprise** [comment]
I don't get this line
> users << OpenStruct.new({name: "tester#{i}", email: "test#{i}@example.com"})

Where does "users" come from?

**Comment by zawaideh** [comment]
This is just an example. Just put in a query or an array of objects that respond to email and name. E.g. if you have a Users table you can just put in `Users.where(unsubscribed: false)`

**Comment by edenenterprise** [comment]
It works now, thanks!
