### ISSUE TITLE
Getting this error "ActionView::Template::Error: No route matches {}"

### ISSUE THREAD

**Issue by squarebing** [Sandglaz/maktoub#7]
I am testing maktoub with delayed jobs. but I am having some issues. Could you please help.

> rake maktoub:test['welcome']
...
2014-01-16T20:22:53-0800: [Worker(delayed_job host:ubuntu pid:4342)] Job Class#publish (id=24) RUNNING
  Rendered maktoub/newsletters/welcome.erb within layouts/maktoub/newsletter_mailer (0.9ms)
  Rendered layouts/maktoub/_styles.erb (0.4ms)
2014-01-16T20:22:53-0800: [Worker(delayed_job host:ubuntu pid:4342)] Job Class#publish (id=24) FAILED (0 prior attempts) with ActionView::Template::Error: No route matches {}
...

**Comment by zawaideh** [comment]
closing. Re-open if you're still having trouble.

**Comment by davidpatters0n** [comment]
Just encountered the same above issue. My setup is as followed: 

```ruby 
  mount Maktoub::Engine => '/maktoub'
```

I have a template named: 'test_template' which is under `maktoub/newsletter`. Now when I visit /maktob/test_template I receive `No route matches [GET] "/maktoub/test_template"` ?

Using:  Ruby 2.1.2/ Rails 4.1.5

**Comment by zawaideh** [comment]
it would be under `maktoub/newsletters/test_templates`

**Comment by davidpatters0n** [comment]
@zawaideh got it. I think the readme needs slightly readjusting: https://github.com/Sandglaz/maktoub#view-in-browser I think it should read as: 

To be able to view your newsletter in a browser add it to routes.rb.
  - mount the engine at a path of your choice.
  - Providing you set your engine route as: `mount Maktoub::Engine => '/'` you would access it as followed:
    - http://example.com/newsletter/my_awesome_newletter

**Comment by zawaideh** [comment]
updated. Thanks for the suggestion.
